services:
  db:
    container_name: meal-planner-db
    image: postgres
    environment:
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: local-password
      PGDATA: /data/postgres
      POSTGRES_DB: meal-planner
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db: # Define o volume utilizado pelo serviço

networks:
  db: # Define a rede referenciada no serviço